coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        # Require 50% coverage on PRs, warn at 40%
        threshold: 50%
        flags:
          - unittests

ignore:
  - tests
  - "*/__pycache__/*"
  - "*/site-packages/*"

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: no
